{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "llm-workload.fullname" . }}
  labels:
    {{- include "llm-workload.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "llm-workload.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_label_aiplatform_io_environment]
          targetLabel: environment
        - targetLabel: workload
          replacement: {{ include "llm-workload.fullname" . }}
        - targetLabel: model
          replacement: {{ .Values.model.name | quote }}
        - targetLabel: engine
          replacement: {{ .Values.engine.type | quote }}
{{- end }}
