"""Render the guardrail run as Markdown (the pull request body)."""

from aiplatform.agent.models import Proposal
from aiplatform.steps.pipeline import Context

ICON = {"ok": "✅", "failed": "❌", "skipped": "⏭️"}


def render(request: str, proposal: Proposal, ctx: Context, provider: str) -> str:
    lines = [
        f"## Proposal: {proposal.summary}",
        "",
        f"**Request:** {request}",
        "",
        f"**Provider:** {provider}",
        "",
        "### Rationale",
        proposal.rationale.strip(),
        "",
        "### Files",
        *[f"- `{f.path}` ({f.action})" for f in proposal.files],
        "",
        "### Guardrails",
        "| Check | Result | Detail |",
        "|---|---|---|",
    ]
    for entry in ctx.get("report", []):
        detail = (entry["detail"] or "").replace("|", "\\|").replace("\n", " ")
        icon = ICON.get(entry["status"], entry["status"])
        lines.append(f"| {entry['step']} | {icon} {entry['status']} | {detail} |")
    if ctx.get("cost") is not None:
        lines += [
            "",
            "### Cost estimate",
            ctx["cost"].markdown(),
            "",
            f"Budget: ${ctx.get('budget', 0):.2f}/month. Prices are list-price estimates "
            "from `policy/prices.yaml`, not a bill.",
        ]
    if proposal.risks:
        lines += ["", "### Reviewer checklist", *[f"- [ ] {r}" for r in proposal.risks]]
    lines += [
        "",
        "---",
        "Generated by `aiplatform propose`. Nothing is applied until this PR is reviewed "
        "and merged; Argo CD deploys merged desired state.",
    ]
    return "\n".join(lines)
